### ISSUE TITLE
Create main file for library

### ISSUE THREAD

**Issue by kailukowiak** [3DLables/3DLabeler#13]
This way we don't have to do form ourlib.filepath import func

**Comment by kailukowiak** [comment]
Also, @mjdacs should we change the Image class name? I don't love it and it's not completely accurate because it's not an image in the classic sense.

What do you thin we should call it.

**Comment by mjdacs** [comment]
Image class name changed to Processor and added to preprocessing.py along with main function, fn for npy packaging, and fn for gcp upload
