### ISSUE TITLE
Neural Network Design

### ISSUE THREAD

**Issue by kailukowiak** [3DLables/3DLabeler#2]
Obviously a lot of work needs to be done on network design but maybe we can clarify some basics like if we are going to need a fully connected layer solution that requires standard input size.

**Comment by mjdacs** [comment]
I need to take a small step back and really understand the definition of fully connected layers, standard input size (i think this pertains to different image sizes), cNN, aNN, etc.

**Comment by kailukowiak** [comment]
Lets move this to just updating the wiki in the research section. Then hopefully you can just modify the research wiki to be your submission,
